### ISSUE TITLE
[PSW] - Prototipagem

### ISSUE THREAD

**Issue by natanbalthazar** [dsm-cefet-rj/ti-2023-1-grupo3#15]
[Todos fizeram]

- [x] Discussão das Ideias
- [x] Descrição do Business Case
- [x] Processo de Negócio Principal
- [x] Definição das Entidades e seus Responsáveis
- [x] Definição de Casos de Uso
- [x] Matriz Perfil x Funcionalidade
- [x] Construção da Matriz CRUD
- [x] Priorização de Requisitos
