### ISSUE TITLE
[PSW] - Front-End

### ISSUE THREAD

**Issue by natanbalthazar** [dsm-cefet-rj/ti-2023-1-grupo3#16]
# Tarefas a serem realizadas:

## - [] Prototipação em HTML e Responsividade

- [x] Tela Inicial - Responsável: Pedro
- [ ] Tela de Informação do Paciente - Responsável: Pedro
- [x] Tela de Informação do Profissional - Responsável: Pedro e Edson
- [x] Tela de Marcar Consulta - Responsável: Daniel e Pedro

### - [ ] Criação de Rotas

- [x] Rota dos Profissionais - Responsável: Pedro
- [x] Rota do Perfil - Responsável: Pedro
- [x] Rota Marcação de Consulta  - Responsável: Daniel
- [x] Rota de Cadastro  - Responsável: Daniel
- [x] Rota de Busca - Responsável: Pedro
- [x] Rota de Consultas Marcadas  - Responsável: Edson
- [x] Rota de Login  - Responsável: Daniel
- [x] Rota de Página Inicial - Responsável: Pedro

### - [ ] Gerenciamento de Estado

- [x] Estado dos Profissionais - Responsável: Pedro
- [x] Estado do Perfil - Responsável: Pedro
- [x] Estado de Marcação de Consulta - Responsável: Pedro
- [x] Estado de Cadastro - Responsável: Pedro
- [x] Estado de Busca - Responsável: Pedro
- [x] Estado de Consultas Marcadas - Responsável: Pedro
- [x] Estado de Login - Responsável: Pedro
- [x] Estado de Página Inicial - Responsável: Pedro

### - [ ] Gerenciamento de Eventos

- [x] Evento de Informações dos Profissionais - Responsável: Pedro
- [x] Evento de Atualização de Usuário - Responsável: Pedro
- [x] Evento de Marcação de Consulta - Responsável: Pedro
- [x] Evento de Cadastro de Usuário - Responsável: Pedro
- [x] Evento de Cadastro de Localidade - Responsável: Pedro
- [x] Evento de Busca - Responsável: Pedro
- [x] Evento de Consultas Marcadas - Responsável: Pedro
- [x] Evento de Login - Responsável: Pedro
- [x] Evento de Página Inicial - Responsável: Pedro

### - [ ] Componentização de Páginas

- [x] Página dos Profissionais - Responsável: Pedro
- [ ] Página de Perfil (Não tem) - Responsável: Pedro
- [x] Página de Marcação de Consulta - Responsável: Daniel e Pedro
- [x]  Página de Cadastro - Responsável: Daniel e Pedro
- [x] Página de Busca - Responsável: Pedro
- [x] Página de Consultas Marcadas - Responsável: Edson e Pedro
- [x] Página de Login - Responsável: Daniel e Pedro
- [x] Página Inicial - Responsável: Pedro

**Comment by natanbalthazar** [comment]
Data prevista de entrega: 25/04/2023

**Comment by natanbalthazar** [comment]
Foi resolvido por **Cancelar** as tarefas que não foram feitas.
