### ISSUE TITLE
[PSW] - Back-End

### ISSUE THREAD

**Issue by natanbalthazar** [dsm-cefet-rj/ti-2023-1-grupo3#17]
# Tarefas a serem realizadas:

### - [ ] Criação de Rotas

- [ ] Rota de consulta - Responsável: Edson
- [x] Rota de usuário (2h) - Responsável: Pedro
- [x] Rota de profissionais (2h) - Responsável: Pedro
- [ ] Rotas de localidade - Responsável: Daniel

### - [ ] Modelagem de Banco de Dados

- [x] Interação com MongoDB com Back (1h) - Responsável: Pedro

### - [ ] Criação de Collections

- [ ] Criação de Collections: Consulta - Responsável: Edson
- [x] Criação de Collections: Usuário (30min) - Responsável: Pedro
- [x] Criação de Collections: Profissionais (30min) - Responsável: Pedro
- [ ] Criação de Collections: Localidade - Responsável: Daniel

### - [ ] Criação de serviços e operações no MongoDB

- [ ] Serviços de Consulta - Responsável: Edson
- [x] Serviços de Profissional (2h) - Responsável: Pedro
- [x] Serviços de Usuário (2h) - Responsável: Pedro
- [ ] Serviços de Localidade - Responsável: Daniel

**Comment by natanbalthazar** [comment]
Data prevista de entrega: 17/07/2023
